steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=dockerhub --format='get(payload.data)' | tr '_-' '/+' | base64 -d > decrypted-data.txt" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: [ '-c', 'docker login --username=cshou --password-stdin < decrypted-data.txt']
- id: Build dockerfile
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=cshou/cectl:alpine-latest
  - --tag=cshou/cectl:alpine-${BRANCH_NAME}
  - --file=build/Dockerfile-alpine
  - .
images:
- cshou/cectl:alpine-latest
- cshou/cectl:alpine-${BRANCH_NAME}