steps:
  - id: Build dockerfile
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=cshou/cectl:alpine-latest
      - --tag=cshou/cectl:alpine-${BRANCH_NAME}
      - --file=build/Dockerfile-alpine
      - .
images:
  - cshou/cectl:alpine-latest
  - cshou/cectl:alpine-${BRANCH_NAME}